routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::middleware(['auth'])->group(function() {
    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index')->name('home');
//    =====================================TASKS======================================
    Route::get('/teams/my-teams', 'TeamsController@myIndex')->name('teams.my-team');
    Route::resource('teams', 'TeamsController');

//    =====================================TASKS======================================
    Route::put('tasks/abort/{task}', 'TasksController@abort')->name('tasks.abort');
    Route::put('tasks/decline/{task}', 'TasksController@decline')->name('tasks.decline');
    Route::put('tasks/complete/{task}', 'TasksController@complete')->name('tasks.complete');
    Route::put('tasks/resolve/{task}', 'TasksController@resolve')->name('tasks.resolve');
    Route::put('tasks/unresolve/{task}', 'TasksController@unresolve')->name('tasks.unresolve');
    Route::get('tasks/reassign/{task}', 'TasksController@reassign')->name('tasks.reassign');
    Route::post('tasks/reassign/{task}', 'TasksController@storeReassign')->name('tasks.reassign');
    Route::get('tasks/my-tasks', 'TasksController@myIndex')->name('tasks.my-tasks');
    Route::get('user-tasks/view/{user}', 'TasksController@userIndex')->name('tasks.user-tasks');
    Route::get('team-tasks/view/{team}', 'TasksController@teamIndex')->name('tasks.team-tasks');
    Route::resource('tasks', 'TasksController');
    Route::get('user-tasks/assign/{user}', 'TasksController@createWithUser')->name('tasks.createWithUser');
    Route::get('team-tasks/assign/{team}', 'TasksController@createWithTeam')->name('tasks.createWithTeam');
    Route::post('tasks/user', 'TasksController@storeAssignedTask')->name('tasks.storeAssignedTask');
    //
    Route::get('score/{user}/{year}','HomeController@score')->name('user.score');
    Route::get('updateBestMember', function () {
        \App\Team::updateBestMembers();
        return redirect()->back();
    })->name('team.updateBestMembers');
});

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    //
    protected $fillable = ['title', 'deadline_at', 'created_by', 'priority', 'team_id'];
    protected $dates = ['deadline_at', 'completed_at'];


    /*
     * RELATIONSHIP METHODS
     */
    public function team(){
        return $this->belongsTo(Team::class);
    }
    public function user(){
        return $this->belongsToMany(User::class);
    }
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Tasks\CreateTaskRequest;
use App\Http\Requests\Tasks\ReassignTaskRequest;
use App\Http\Requests\Teams\CreateTeamRequest;
use App\Task;
use App\Team;
use App\User;
use http\Env\Url;
use Illuminate\Http\Request;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class TasksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
    }
    public function myIndex(){
        $user = auth()->user();
        return view('tasks.my_tasks', compact('user'));
    }
    public function userIndex(User $user){
        $this->authorize('viewAny', Task::class);
        return view('tasks.my_tasks', compact('user'));
    }
    public function teamIndex(Team $team){
        $this->authorize('view', $team);
        return view('tasks.teams_tasks', compact('team'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $teams = Team::all();
        return view('tasks.create', compact([
            'teams'
        ]));
    }
    public function createWithUser(User $user){
        return view('tasks.create', compact([
            'user'
        ]));
    }
    public function createWithTeam(Team $team){
        return view('tasks.create', compact([
            'team'
        ]));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTaskRequest $request)
    {
        //
        $task = Task::create([
            'title'=>$request->title,
            'description'=>$request->description,
            'created_by'=>auth()->id(),
            'priority'=>$request->priority,
            'team_id'=>$request->team_id
        ]);

        return redirect(route('teams.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function show(Task $task)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Task $task)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function destroy(Task $task)
    {
        //
    }
    public function storeAssignedTask(CreateTaskRequest $request){
        $user = User::find($request->member_id);
        $user->tasks()->attach($request->task_id, ['status'=>'PENDING']);
        foreach ($request->task_id as $task){
            $task = Task::find($task);
            $task->status = 'PENDING';
            if(isset($request->deadline_at)){
                $task->deadline_at = $request->deadline_at;
            }
            $task->save();
        }
        //redirect to dashboard
        return redirect(route('teams.index'));
    }
    public function complete(Request $request, Task $task){
        $task->status = "COMPLETED";
        $task->response = $request->response;
        $task->save();
        DB::table('task_user')->where('task_id', '=', $task->id)->update(['status'=>'COMPLETED', 'completed_at'=>Carbon::now()]);
        return redirect()->back();
    }
    public function abort(Request $request, Task $task){
        $this->authorize('abort', $task);
        $task->user[0]->tasks()->updateExistingPivot($task->id, ['status'=>'RELINQUISHED']);
        $task->response = $request->abort_reason;
        $task->status = "ABORTED";
        $task->save();
        return redirect()->back();
    }
    public function decline(Task $task){
        $task->status = "DECLINED";
        $task->save();
        $task->user[0]->tasks()->updateExistingPivot($task->id, ['status'=>'DECLINED']);
        return redirect()->back();
    }
    public function resolve(Task $task){
        $task->status = "RESOLVED";
        $task->save();
        $task->user[0]->tasks()->updateExistingPivot($task->id, ['status'=>'RESOLVED']);
        return redirect()->back();
    }
    public function unresolve(Task $task){
        $task->status = "REJECTED";
        $task->save();
        $task->user[0]->tasks()->updateExistingPivot($task->id, ['status'=>'REJECTED']);
        return redirect()->back();
    }
    public function reassign(Task $task){
        $team = Team::find($task->team_id);
        return view('tasks.reassign', compact([
            'team', 'task'
        ]));
    }
    public function storeReassign(ReassignTaskRequest $request, Task $task){
        $task->status = "PENDING";
        $task->save();
        $user = User::find($request->member_id);
        $user->tasks()->attach($task->id, ['status'=>'PENDING']);
        return redirect('home');
    }
}

resources/views/tasks/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="card">
        <div class="card-header">
            <p class="m-0">
                @if(!((isset($team)) || (isset($user))))
                    Create Task
                @else
                    Assign Task
                @endif
            </p>
        </div>

        <div class="card-body">
            @if( (isset($user) &&  ($user->team[0]->tasks->whereNull('status')->count() == 0 )) || (isset($team) &&  ($team->tasks->whereNull('status')->count() == 0 )))
                <p>No Tasks for this team!</p>
                <a href="{{route('tasks.createWithTeam', $user->team[0])}}" class="btn btn-info text-white">Create Task</a>
            @else
                <form action="
                    @if(!((isset($team)) || (isset($user))))
                        {{ route('tasks.store') }}
                    @else
                        {{route('tasks.storeAssignedTask')}}
                    @endif
                "
                method="POST">
                @csrf

                    <!-- TITLE -->
                    @if(!((isset($team)) || (isset($user))))
                        <div class="form-group">
                            <label for="name">Title</label>
                            <input type="text"
                                   value="{{ old('title') }}"
                                   class="form-control @error('title') is-invalid @enderror"
                                   name="title" id="title">
                            @error('title')
                            <p class="text-danger">{{ $message }}</p>
                            @enderror
                        </div>

                        <!-- DESCRIPTION -->
                        <div class="form-group">
                            <label for="description">Description</label>
                            <textarea
                                class="form-control @error('description') is-invalid @enderror"
                                name="description" id="description">{{ old('description') }}</textarea>
                            @error('description')
                            <p class="text-danger">{{ $message }}</p>
                            @enderror
                        </div>
                        <!-- END DESCRIPTION -->

                        <!-- PRIORITY -->
                        <div class="form-group">
                            <label for="priority">Priority</label>
                            <div>
                                <input type="range" min="1" max="10" class="d-inline range-slider @error('priority') is-invalid @enderror" value="1" step="1" name="priority">
                                <span id="range-value">1</span>
                                @error('priority')
                                <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                        </div>
                        <!-- END PRIORITY -->

                        <!-- DEADLINE -->
                        <div class="form-group">
                            <label for="deadline_at">Deadline</label>
                            <input type="text"
                                   placeholder="Select Date"
                                   value="{{ old('deadline_at') }}"
                                   class="form-control"
                                   name="deadline_at" id="deadline_at">
                            @error('deadline_at')
                            <p class="text-danger">{{ $message }}</p>
                            @enderror
                        </div>
                        <!-- END DEADLINE -->
                    @else
                        <div class="form-group">
                            <label for="task_id">Select Task Title</label>
                            <select class="form-control" name="task_id[]" id="task_id" multiple>
                                @foreach((isset($user)) ? $user->team[0]->tasks->whereNull('status') : $team->tasks as $task)
                                    <option value="{{$task->id}}">{{$task->title}}</option>
                                @endforeach
                            </select>
                            @error('task_id')
                            <p class="text-danger">{{ $message }}</p>
                            @enderror
                        </div>
                    @endif
                    <!-- END TITLE -->

                    @if(!((isset($team)) || (isset($user))))
                    <!-- TEAM -->
                        <div class="form-group">
                            <label for="team_id">Select Team</label>
                            <select name="team_id" id="team_id" class="form-control @error('team_id') is-invalid @enderror">
                                <option value="">Select Team</option>
                                @foreach($teams as $team)
                                    <option value="{{$team->id}}">{{\Illuminate\Support\Str::ucfirst($team->name)}}</option>
                                    @unset($team)
                                @endforeach
                            </select>
                            @error('team_id')
                            <p class="text-danger">{{ $message }}</p>
                            @enderror
                        </div>
                    <!-- END TEAM -->
                    @endif

                    @if(isset($user))
                        <!-- MEMBERS -->
                        <div class="form-group">
                            <label for="member_id">Select Team Member</label>
                            <select name="member_id" id="member_id" class="form-control @error('member_id') is-invalid @enderror">
                                <option value="">Select Member</option>
                                @if(isset($team))
                                    @foreach ($team->members as $member)
                                        <option value="{{$member->id}}"}} {{(old('member_id') == $member->id) ? 'selected' : ''}}>{{ $member->name }}</option>
                                    @endforeach
                                @endif
                                @if(isset($user))
                                    <option selected value="{{$user->id}}">{{$user->name}}</option>
                                @endif
                            </select>
                            @error('member_id')
                            <p class="text-danger">{{ $message }}</p>
                            @enderror
                        </div>
                        <!-- END MEMBERS -->

                            <!-- DEADLINE -->
                            <div class="form-group">
                                <label for="deadline_at">Deadline</label>
                                <input type="text"
                                       placeholder="Select Date"
                                       value="{{ old('deadline_at') }}"
                                       class="form-control"
                                       name="deadline_at" id="deadline_at">
                                @error('deadline_at')
                                <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                            <!-- END DEADLINE -->
                    @endif
                    @if(isset($team))
                        <p>Hello!</p>
                    @endif

                    <!-- SUBMIT BUTTON -->
                    <div class="form-group">
                        <button class="btn btn-success float-right" type="submit">
                            @if(!((isset($team)) || (isset($user))))
                                Create
                            @else
                                Assign
                            @endif
                        </button>
                        <div class="clearfix"></div>
                    </div>
                    <!-- END SUBMIT BUTTON -->

                </form>
            @endif
        </div>
    </div>
@endsection
@section('page-level-scripts')
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script>
        flatpickr("#deadline_at", {
            enableTime: true
        });
        $('.range-slider').on('input', function () {
            console.log($('#range-value'));
            document.getElementById('range-value').innerHTML = this.value;
        });
    </script>
@endsection
@section('page-level-styles')
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <style>
        #range-value {
            display: inline-block;
            position: relative;
            color: #fff;
            line-height: 20px;
            text-align: center;
            border-radius: 3px;
            background: #005CC8;
            padding: 5px 10px;
            margin-left: 8px;
        }
        #range-value:after {
            position: absolute;
            top: 8px;
            left: -7px;
            width: 0;
            height: 0;
            border-top: 7px solid transparent;
            border-right: 7px solid #005CC8;
            border-bottom: 7px solid transparent;
            content: '';
        }
        .range-slider{
            cursor: pointer;
        }
    </style>
@endsection

resources/views/tasks/reassign.blade.php
@extends('layouts.app')
@section('content')
    <div class="card">
        <div class="card-header">
            <p class="m-0">
                Reassign Task
            </p>
        </div>

        <div class="card-body">
            <form action="{{route('tasks.reassign', $task)}}" method="POST">
                @csrf
                <!-- TITLE -->
                <div class="form-group">
                    <label for="name">Title</label>
                    <input type="text"
                           value="{{ $task->title }}"
                           class="form-control"
                            disabled>
                </div>
                <!-- END TITLE -->

                <!-- DESCRIPTION -->
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea
                        class="form-control" disabled>{{$task->description}}</textarea>
                </div>
                <!-- END DESCRIPTION -->

                <!-- DEADLINE -->
                <div class="form-group">
                    <label for="deadline_at">Deadline</label>
                    <input type="text"
                           placeholder="Select Date"
                           value="{{ $task->deadline_at }}"
                           class="form-control"
                           name="deadline_at" id="deadline_at">
                    @error('deadline_at')
                    <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <!-- END DEADLINE -->

                <!-- MEMBERS -->
                <div class="form-group">
                    <label for="member_id">Select Team Member</label>
                    <select name="member_id" id="member_id" class="form-control @error('member_id') is-invalid @enderror">
                        <option value="">Select Member</option>
                        @if(isset($team))
                            @foreach ($team->members as $member)
                                <option value="{{$member->id}}"}} {{(old('member_id') == $member->id) ? 'selected' : ''}}>{{ $member->name }}</option>
                            @endforeach
                        @endif
                        @if(isset($user))
                            <option selected value="{{$user->id}}">{{$user->name}}</option>
                        @endif
                    </select>
                    @error('member_id')
                    <p class="text-danger">{{ $message }}</p>
                    @enderror
                </div>
                <!-- END MEMBERS -->

                <!-- SUBMIT BUTTON -->
                <div class="form-group">
                    <button class="btn btn-success float-right" type="submit">
                        Reassign
                    </button>
                    <div class="clearfix"></div>
                </div>
                <!-- END SUBMIT BUTTON -->
            </form>
        </div>
    </div>
@endsection
@section('page-level-scripts')
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script>
        flatpickr("#deadline_at", {
            enableTime: true,
        });
        $('#deadline_at').removeAttr('readonly');
    </script>
@endsection
@section('page-level-styles')
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
@endsection

resources/views/tasks/teams_tasks.blade.php
@extends('layouts.app')
{{--{{dd(auth()->user()->declinedTasks())}}--}}

@section('page-level-styles')
    <style>
        .task-card {
            padding: 1.25rem;
            margin-top: 1.25rem;
            margin-bottom: 1.25rem;
            border: 1px solid #eee;
            border-left-width: .25rem;
            border-radius: .25rem;
        }
        .task-warning{
            border-left-color: #f0ad4e;
        }
        .task-danger{
            border-left-color: #dd1010;
        }
        .task-safe{
            border-left-color: #23c11d;
        }
        .task-card:hover{
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        }
    </style>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
@endsection
@section('content')
    @can('assign', \App\Task::class)
        <div class="d-flex justify-content-end mb-3">
            <a href="{{route('tasks.createWithTeam', $team->id)}}" class="btn btn-primary">Assign Task</a>
        </div>
    @endcan
    <div class="card">
        <div class="card-header">
            <ul class="nav nav-pills card-header-pills" id="tasks" role="tablist">
                <li class="nav-item" >
                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#pending" role="tab" aria-controls="home" aria-selected="true">Tasks Pending</a>
                </li>
                <li class="nav-item" >
                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#completed" role="tab" aria-controls="profile" aria-selected="false">Tasks Completed</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#resolved" role="tab" aria-controls="contact" aria-selected="false">Tasks Resolved</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#unresolved" role="tab" aria-controls="contact" aria-selected="false">Tasks Unresolved</a>
                </li>
            </ul>
        </div>
        <div class="card-body">
            <div class="mt-3">

                <div class="tab-content" id="myTabContent">
                    <div class="mt-4 tab-pane fade show active" id="pending" role="tabpanel" aria-labelledby="home-tab">
                        @if($team->tasks()->where('status', 'PENDING')->count())
                            @foreach($team->tasks->where('status', 'PENDING') as $task)
                                <div class="task-card
                                    @if(($diff = \Carbon\Carbon::parse($task->deadline_at)->diffInDays(\Carbon\Carbon::now())) <= 1)
                                    task-danger
                                    @elseif(($diff = \Carbon\Carbon::parse($task->deadline_at)->diffInDays(\Carbon\Carbon::now())) <= 3)
                                    task-warning
                                    @else
                                    task-safe
                                    @endif
                                    ">
                                    <div>
                                        <div class="float-left">
                                            <h5 id="conveying-meaning-to-assistive-technologies">{{$task->title}}</h5>
                                        </div>
                                        <div class="float-right">
                                            @if(($diff = \Carbon\Carbon::parse($task->deadline_at)->diffInDays(\Carbon\Carbon::now())) <= 1)
                                                <p class="text-danger">{{$task->deadline_at->diff(\Carbon\Carbon::now())->format('%H:%I:%S')}} Hours Remaining</p>
                                            @else
                                                <p class="text-success">{{$task->deadline_at->diffForHumans()}}</p>
                                            @endif
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <p>@if($task->description) {{\Illuminate\Support\Str::limit($task->description, 200)}} @else <p>No Description!</p>@endif</p>
                                    <div class="mt-4">
                                        <p class="float-left">Assigned To: <span class="text-success">{{$task->user[0]->name}}</span></p>
                                        @can('abort', $task)
                                            <a href="" class="btn btn-danger float-right"
                                               data-toggle="modal"
                                               onclick="displayModalForm({{$task}})" data-target="#abortModal">Abort</a>
                                        @endcan
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            @endforeach
                        @else
                            <p>No Pending Tasks</p>
                        @endif
                    </div>
                    <div class="tab-pane fade" id="completed" role="tabpanel" aria-labelledby="profile-tab">Completed</div>
                    <div class="tab-pane fade" id="resolved" role="tabpanel" aria-labelledby="contact-tab">Resolved</div>
                    <div class="tab-pane fade" id="unresolved" role="tabpanel" aria-labelledby="contact-tab">Unresolved</div>
                </div>
            </div>
        </div>
    </div>

    <!-- ABORT MODAL -->
    <div class="modal fade" id="abortModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Abort Task</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="" method="POST" id="abortForm">
                    <div class="modal-body">
                        @csrf
                        @method('put')
                        <div class="form-group">
                            <label for="abort_reason" class="col-form-label">Aborting Reason:</label>
                            <textarea name="abort_reason" class="form-control" id="abort_reason"></textarea>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-danger">Abort</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('page-level-scripts')
    <script type="text/javascript">
        function displayModalForm($task) {
            var url = '/tasks/abort/' + $task.id;
            $("#abortForm").attr('action', url);
        }
    </script>
@endsection