routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
Route::middleware(['auth'])->group(function() {
    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index')->name('home');
//    =====================================TASKS======================================
    Route::get('/teams/my-teams', 'TeamsController@myIndex')->name('teams.my-team');
    Route::resource('teams', 'TeamsController');

//    =====================================TASKS======================================
    Route::put('tasks/abort/{task}', 'TasksController@abort')->name('tasks.abort');
    Route::put('tasks/decline/{task}', 'TasksController@decline')->name('tasks.decline');
    Route::put('tasks/complete/{task}', 'TasksController@complete')->name('tasks.complete');
    Route::put('tasks/resolve/{task}', 'TasksController@resolve')->name('tasks.resolve');
    Route::put('tasks/unresolve/{task}', 'TasksController@unresolve')->name('tasks.unresolve');
    Route::get('tasks/reassign/{task}', 'TasksController@reassign')->name('tasks.reassign');
    Route::post('tasks/reassign/{task}', 'TasksController@storeReassign')->name('tasks.reassign');
    Route::get('tasks/my-tasks', 'TasksController@myIndex')->name('tasks.my-tasks');
    Route::get('user-tasks/view/{user}', 'TasksController@userIndex')->name('tasks.user-tasks');
    Route::get('team-tasks/view/{team}', 'TasksController@teamIndex')->name('tasks.team-tasks');
    Route::resource('tasks', 'TasksController');
    Route::get('user-tasks/assign/{user}', 'TasksController@createWithUser')->name('tasks.createWithUser');
    Route::get('team-tasks/assign/{team}', 'TasksController@createWithTeam')->name('tasks.createWithTeam');
    Route::post('tasks/user', 'TasksController@storeAssignedTask')->name('tasks.storeAssignedTask');
    //
    Route::get('score/{user}/{year}','HomeController@score')->name('user.score');
    Route::get('updateBestMember', function () {
        \App\Team::updateBestMembers();
        return redirect()->back();
    })->name('team.updateBestMembers');
});

resources/views/layouts/includes/_navigation.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/includes/_sidebar.blade.php
{{--<ul class="list-group">--}}
{{--    <li class="list-group-item">--}}
{{--        <a href="">Users</a>--}}
{{--    </li>--}}
{{--    <li class="list-group-item">--}}
{{--        <a href="{{route('teams.index')}}">Teams</a>--}}
{{--    </li>--}}
{{--    <li class="list-group-item">--}}
{{--        <a href="{{route('tasks.index')}}">Tasks</a>--}}
{{--    </li>--}}
{{--</ul>--}}
{{--<ul class="list-group mt-3">--}}
{{--    <li class="list-group-item">--}}
{{--        <a href=""></a>--}}
{{--    </li>--}}
{{--</ul>--}}
    <!-- Sidebar -->
    <div id="sidebar-container" class="sidebar-expanded d-none d-md-block">
        <!-- d-* hiddens the Sidebar in smaller devices. Its itens can be kept on the Navbar 'Menu' -->
        <!-- Bootstrap List Group -->
        <ul class="list-group">

            <a href="#" class="bg-white list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-start align-items-center">
                    <span class="fa fa-users fa-fw mr-3"></span>
                    <span class="menu-collapsed">Users</span>
                    <span class="submenu-icon ml-auto"></span>
                </div>
            </a>

            <a href="#teams-menu" data-toggle="collapse" aria-expanded="false" class="bg-white list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-start align-items-center">
                    <span class="fa fa-users fa-fw mr-3"></span>
                    <span class="menu-collapsed">Teams</span>
                    <span class="submenu-icon ml-auto"></span>
                </div>
            </a>

            <div id='teams-menu' class="collapse sidebar-submenu">
                @can('viewAllTeams', \App\Team::class)
                    <a href="{{route('teams.index')}}" class="list-group-item list-group-item-action bg-white">
                        <span class="menu-collapsed">All Teams</span>
                    </a>
                @endcan
                <a href="{{route('teams.my-team')}}" class="list-group-item list-group-item-action bg-white">
                    <span class="menu-collapsed">My Teams</span>
                </a>
            </div>

            <!-- Menu with submenu -->
            <a href="#tasks-menu" data-toggle="collapse" aria-expanded="false" class="bg-white list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-start align-items-center">
                    <span class="fa fa-dashboard fa-fw mr-3"></span>
                    <span class="menu-collapsed">Tasks</span>
                    <span class="submenu-icon ml-auto"></span>
                </div>
            </a>
            <!-- Submenu content -->

            <div id='tasks-menu' class="collapse sidebar-submenu">
                @can('create', \App\Task::class)
                    <a href="{{route('tasks.create')}}" class="list-group-item list-group-item-action bg-white">
                        <span class="menu-collapsed">Create Task</span>
                    </a>
                    <a href="#" class="list-group-item list-group-item-action bg-white">
                        <span class="menu-collapsed">View Unassigned Tasks</span>
                    </a>
                @endcan
                <a href="{{route('tasks.my-tasks')}}" class="list-group-item list-group-item-action bg-white">
                    <span class="menu-collapsed">My Tasks</span>
                </a>
            </div>
            <a href="#submenu2" data-toggle="collapse" aria-expanded="false" class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-start align-items-center">
                    <span class="fa fa-user fa-fw mr-3"></span>
                    <span class="menu-collapsed">Profile</span>
                    <span class="submenu-icon ml-auto"></span>
                </div>
            </a>
            <!-- Submenu content -->
            <div id='submenu2' class="collapse sidebar-submenu">
                <a href="#" class="list-group-item list-group-item-action bg-white">
                    <span class="menu-collapsed">Settings</span>
                </a>
                <a href="#" class="list-group-item list-group-item-action bg-white">
                    <span class="menu-collapsed">Password</span>
                </a>
            </div>
        </ul>
    </div>
<style>

    /* Closed submenu icon */
    #sidebar-container .list-group .list-group-item[aria-expanded="false"] .submenu-icon::after {
        content: " \f0d7";
        font-family: FontAwesome;
    }
    /* Opened submenu icon */
    #sidebar-container .list-group .list-group-item[aria-expanded="true"] .submenu-icon::after {
        content: " \f0da";
        font-family: FontAwesome;
    }
</style>